name: RisingTone
description: A new way to master Chinese's tones

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  bloc_concurrency: ^0.2.2
  built_collection: ^5.1.1
  built_value: ^8.7.0
  collection: ^1.18.0
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  # flutter_form_bloc: ^0.31.0
  flutter_form_bloc:
    git:
      url: https://github.com/Cavin6080/form_bloc.git
      path: packages/flutter_form_bloc
  just_audio: ^0.9.36
  just_audio_mpv: ^0.1.7
  http: ^1.1.0
  hydrated_bloc: ^9.1.2
  path: ^1.8.2
  path_provider: ^2.1.1
  percent_indicator: ^4.2.3
  uuid: ^3.0.7
  optional: ^6.1.0+1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  built_value_generator: ^8.4.4
  flutter_lints: ^3.0.1
  test: ^1.24.9
  path_provider_platform_interface: any
  plugin_platform_interface: any
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/tonedata.db3
    - assets/orderedWordList.json
    - assets/skilltree.json
    - assets/images/risingtone_logo.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true

#dependency_overrides:
#  intl: ^0.18.0